# Generated by Django 3.2.12 on 2022-12-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('adresa', models.CharField(max_length=50)),
                ('cijena_noci', models.IntegerField(max_length=3)),
                ('max_gosti', models.IntegerField(max_length=2)),
                ('min_br_nocenja', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Gost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('drzava', models.CharField(max_length=30)),
                ('grad', models.CharField(max_length=50)),
                ('oib', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
                ('broj_nocenja', models.IntegerField(max_length=2)),
                ('cijena_ukupno', models.IntegerField(max_length=5)),
                ('apartman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.apartman')),
                ('gost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gost')),
            ],
        ),
    ]
