# Generated by Django 3.2.12 on 2022-12-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartman',
            name='cijena_noci',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartman',
            name='max_gosti',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartman',
            name='min_br_nocenja',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gost',
            name='oib',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='broj_nocenja',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='cijena_ukupno',
            field=models.IntegerField(),
        ),
    ]
