# Generated by Django 3.2.12 on 2023-02-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_apartman_broj_zvezdica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='apartman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartman'),
        ),
    ]
