# Generated by Django 3.2.12 on 2022-12-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221220_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='gost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.gost'),
        ),
    ]
